# Generated by Django 3.0.3 on 2020-04-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
