# Generated by Django 3.0.3 on 2020-04-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no_of_minutes', models.IntegerField()),
                ('points', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='MovementReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MovementReasons',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.IntegerField()),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('photo_url', models.URLField(max_length=1500)),
                ('signup_by', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserIsolationLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('lattitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('city_lat', models.CharField(max_length=255)),
                ('city_long', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('state_lat', models.CharField(max_length=255)),
                ('state_long', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('country_lat', models.CharField(max_length=255)),
                ('country_long', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('is_default', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UserIsolationLocations',
            },
        ),
        migrations.CreateModel(
            name='UserLevelScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('level_id', models.IntegerField()),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UserLevelScores',
            },
        ),
        migrations.CreateModel(
            name='userLocationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_group_code', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('iso_location_id', models.CharField(max_length=255)),
                ('lattitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('dist_from_deafult', models.FloatField()),
                ('points', models.IntegerField()),
                ('verified', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UserLocationHistories',
            },
        ),
        migrations.CreateModel(
            name='UserMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('movement_reason_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UserMovements',
            },
        ),
    ]
