# Generated by Django 3.0.3 on 2020-04-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userisolationlocation',
            name='city_lat',
        ),
        migrations.RemoveField(
            model_name='userisolationlocation',
            name='city_long',
        ),
        migrations.RemoveField(
            model_name='userisolationlocation',
            name='country_lat',
        ),
        migrations.RemoveField(
            model_name='userisolationlocation',
            name='country_long',
        ),
        migrations.RemoveField(
            model_name='userisolationlocation',
            name='state_lat',
        ),
        migrations.RemoveField(
            model_name='userisolationlocation',
            name='state_long',
        ),
    ]
