# Generated by Django 3.0.3 on 2020-04-01 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200401_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='userisolationlocation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userlevelscore',
            name='level_id',
        ),
        migrations.RemoveField(
            model_name='userlevelscore',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userlocationhistory',
            name='iso_location_id',
        ),
        migrations.RemoveField(
            model_name='userlocationhistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='rule',
            name='distance_from_isolation_location',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userisolationlocation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlevelscore',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Level'),
        ),
        migrations.AddField(
            model_name='userlevelscore',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlocationhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlocationhistory',
            name='userIsolationLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.UserIsolationLocation'),
        ),
    ]
