# Generated by Django 3.0.3 on 2020-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200401_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='distance_from_isolation_location',
            new_name='max_distance_from_isolation_location',
        ),
        migrations.RemoveField(
            model_name='level',
            name='no_of_minutes',
        ),
        migrations.RemoveField(
            model_name='level',
            name='points',
        ),
        migrations.AddField(
            model_name='level',
            name='max_no_of_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='max_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='min_no_of_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='min_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rule',
            name='min_distance_from_isolation_location',
            field=models.FloatField(default=0.0),
        ),
    ]
